### ISSUE TITLE
 what's the best way to add bound limits?

### ISSUE THREAD

**Issue by AnakinCN** [bhrnjica/gpdotnet#7]
Hi,

First of all, gpdotnet is really a good package for solving intelligent agents.

I wonder what's the best way to add a top level nodes that can do something like:

if ((lowerNodeValue) > upperLimit) return upperLimit;
if ((lowerNodeValue) < lowerLimit) return lowerLimit;

The case is, if I manually add the top level nodes for bound limit, how can I prevent them from being broken by GP operators?

And I am not seeing any constraining mechanism in gpdotnet.

Thanks a lot.

**Comment by bhrnjica** [comment]
Hi AnakinCN, thank you for the comments.

In order to prevent certain node to be destroyed during the operations, omit them from the selection for the operations.

For Example: The [Crossover](https://github.com/bhrnjica/gpdotnet/blob/235f79b969089274a11ced642cbabcc55a33a4f8/Net.Core/GPdotNet.Core/gp/Chromosome.cs#L149) methods first select the node indices to crossover and then perform the operation (Line 153, 154 in `Cromosome.cs` file). So there, you can check if the certain node is selected for the operation and change it if needed.


Hope this will help.

**Comment by AnakinCN** [comment]
Thanks

I hope you could consider add some MaxValue, MinValue property to Chromosome, that would help a lot.
